### ISSUE TITLE
/examples/server.js does not work. :-(

### ISSUE THREAD

**Issue by nelsonic** [swider/express-dust#4]
Hi Nick,
When was the last time you tried to run /examples/**server.js**

I just tried `node /examples/server.js` and got the following warning:

``` sh
Warning: express.createServer() is deprecated, express
applications no longer inherit from http.Server,
please use:

  var express = require("express");
  var app = express();
```

I made that basic change to ./example/**server.js** and then I get the following error:

``` sh
App listening at: http://localhost:8000/
Error: No default engine was specified and no extension was provided.
```

see: https://github.com/nelsonic/express-dust/blob/master/examples/server2.js

Added the line:

``` javascript
app.set('view engine', 'dust');
```

now I get:

```
Error: Cannot find module 'dust'
```

Tried changing the line to:

``` javascript
app.set('view engine', dust);
```

and get:

``` sh
Error: Cannot find module '[object Object]'
```

Any chance you can update this so new people can learn/use your module?
_or_ if you are no longer using this module yourself, what _are_ you using?
Thanks.

**Comment by swider** [comment]
Sorry @nelsonic, I did not update this package for Express 3. If you `npm install express@2.x.x`, everything should work as expected.

**Comment by nelsonic** [comment]
@swider Express 3 was released 14 months ago.
I don't know _anyone_ still using 2.x.x ... 
any chance we can update **express-dust** to use Express > **3**.x.x ?
fairly certain there are (_many_) other people who will find your module useful if they can use it with the latest version of Express. If you have not started work on the update, let me know (so I can help!)

**Comment by swider** [comment]
I've not been doing much new development in node for awhile, so I never had a need to make it compatible. I just did a quick search, looks like the convention now is to use visionmedia/consolidate.js. If that's too much bloat for your project, klei-dev/dust looks like it is actively maintained. If that doesn't meet your needs and you want to take the lead on fixing this package, I'd be willing to work with you on it.

**Comment by nelsonic** [comment]
Closing as no longer use express. see: https://github.com/nelsonic/learn-hapi
